apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  enableCodPayment: {{ .Values.featureFlags.enableCodPayment | quote }}
  enableNewUI: {{ .Values.featureFlags.enableNewUI | quote }} 