apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-toggle-service
  labels:
    app: feature-toggle
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: feature-toggle
  template:
    metadata:
      labels:
        app: feature-toggle
    spec:
      containers:
      - name: feature-toggle
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_USER
          value: {{ .Values.database.user }}
        - name: DB_PASSWORD
          value: {{ .Values.database.password }}
        - name: DB_NAME
          value: {{ .Values.database.name }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: feature-toggle-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: feature-toggle 