apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: {{ .Values.env.REDIS_HOST }}
        - name: REDIS_PORT
          value: {{ .Values.env.REDIS_PORT }}
        - name: REDIS_PASSWORD
          value: {{ .Values.env.REDIS_PASSWORD }}
        - name: PRODUCTS_SERVICE_URL
          value: {{ .Values.env.PRODUCTS_SERVICE_URL }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: cart 