linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - goconst
    - gocyclo
    - dupl
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo

  max-issues-per-linter: 0
  max-same-issues: 0
