linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - prealloc
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - node_modules/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0 