extends: spectral:oas
rules:
  operation-description: error
  operation-tags: error
  operation-tag-defined: error
  parameter-description: error
  no-$ref-siblings: error
  typed-enum: error
  no-unused-components: error
  operation-operationId: error
  path-params: error
  openapi-tags: error
  no-script-tags-in-markdown: error
  response-example: warn
  operation-success-response: error
  no-undefined-server-variable: error
  no-empty-servers: error
  oas3-server-trailing-slash: error
  operation-singular-tag: warn
  path-declarations-must-exist: error
  typed-responses: error 