{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /api/orders(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: order
            port:
              number: {{ .Values.service.port }}
{{- end }} 