replicaCount: 1

image:
  repository: yourusername/ecommerce-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: true
  hostname: localhost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 