replicaCount: 1

image:
  repository: yourusername/ecommerce-feature-toggle
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: feature_toggle

featureFlags:
  enableCodPayment: false
  enableNewUI: true 